on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd ${{ secrets.WORK_DIR }}
          git checkout ${{ secrets.MAIN_BRANCH }}
          git pull
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart fastapi.service
